/** Declaration file generated by dts-gen */

declare module 'arpad' {
  import ELO from 'arpad';

  class arpad {
    constructor(k_factor: number | object, min: number, max: any);
    bothExpectedScores(player_1_rating: number, player_2_rating: number): number[];
    expectedScore(rating: number, opponent_rating: number): number;
    getKFactor(rating: number): number;
    getMax(): number;
    getMin(): number;
    newRating(expected_score: number, actual_score: number, previous_rating: number): number;
    newRatingIfLost(rating: number, opponent_rating: number): number;
    newRatingIfTied(rating: number, opponent_rating: number): number;
    newRatingIfWon(rating: number, opponent_rating: number): number;
    setKFactor(k_factor: number | object): this;
    setMax(maximum: number): this;
    setMin(minimum: number): this;
  }

  export = arpad;
}